// Maps each CRAFT_MAP_SHAPES array index (0-based) to its state/UT name,
// identified visually against the extracted shapes' positions.
export const CRAFT_MAP_STATE_NAMES: string[] = [
  'Rajasthan',        // 0 (source idx 3)
  'Madhya Pradesh',   // 1 (4)
  'Maharashtra',      // 2 (5)
  'Jammu and Kashmir',// 3 (6)
  'Uttar Pradesh',    // 4 (7)
  'Gujarat',          // 5 (8)
  'Karnataka',        // 6 (9)
  'Andhra Pradesh',   // 7 (10)
  'Odisha',           // 8 (11)
  'Chhattisgarh',     // 9 (12)
  'Tamil Nadu',       // 10 (13)
  'Bihar',            // 11 (14)
  'Telangana',        // 12 (15)
  'Arunachal Pradesh',// 13 (16)
  'Assam',            // 14 (17)
  'West Bengal',      // 15 (18)
  'Jharkhand',        // 16 (19)
  'Uttarakhand',      // 17 (20)
  'Himachal Pradesh', // 18 (21)
  'Punjab',           // 19 (22)
  'Haryana',          // 20 (23)
  'Kerala',           // 21 (24)
  'Tripura',          // 22 (25)
  'Meghalaya',        // 23 (26)
  'Nagaland',         // 24 (27)
  'Manipur',          // 25 (28)
  'Mizoram',          // 26 (29)
  'Sikkim',           // 27 (30)
  'Goa',              // 28 (31)
  'Delhi',            // 29 (32)
  'Puducherry',       // 30 (33)
];
